//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Archive.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.DocHistory = new HashSet<DocHistory>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public System.DateTime DateOfDocument { get; set; }
        public int IdType { get; set; }
        public Nullable<int> RelatedDocument { get; set; }
        public int IdStorage { get; set; }
        public int Wardrobe { get; set; }
        public int Folder { get; set; }
        public int IdMnemonicCode { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public string FIO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocHistory> DocHistory { get; set; }
        public virtual MnemonicCode MnemonicCode { get; set; }
        public virtual Status Status { get; set; }
        public virtual Type Type { get; set; }
    }
}
